import "../../assets/01.webp";
import "../../assets/02.png";
import "../../assets/03.png";
import "../../assets/04.png";
import "../../assets/05.png";
import "../../assets/06.png";
import "../../assets/07.svg";
import "../../assets/08.svg";
import "../../assets/09.svg";
import "../../assets/10.svg";
import "../../assets/11.svg";
import "../../assets/12.svg";
import "../../assets/13.png";
import "../../assets/14.png";
import "../../assets/15.png";
import "../../assets/icon.ico";
import "../../assets/logo.png";
import "../../assets/mockup1.webp";
import "../../assets/mockup2.png";
import "../../assets/mockup3.webp";
import "../../assets/mockup4.webp";
import "../../assets/mockupMobile.webp";
import "../../assets/mockupTalplet.webp";
import "../../assets/mockupLabtop.webp";
import "../../assets/mockupFullScreen.webp";
import "../../assets/chart-arrow.png";
import "../../assets/img website/Admin-DashBoard.webp";
import "../../assets/img website/Bootstrap-5-Design-02-Bondi.webp";
import "../../assets/img website/Courses.webp";
import "../../assets/img website/creat-responsev-web-dezain.webp";
import "../../assets/img website/Creat-Templet-with-HTML-Css3-JavaScript.webp";
import "../../assets/img website/creating-a-websit-from-privew-html-css-jQuery-LV3.webp";
import "../../assets/img website/creating-a-websit-from-privew-html-css-jQuery.webp";
import "../../assets/img website/first-design-Bootstrap-3.webp";
import "../../assets/img website/first-design-Bootstrap-4.webp";
import "../../assets/img website/first-design-Bootstrap-5.webp";
import "../../assets/img website/HTML-And-CSS-Template-1.webp";
import "../../assets/img website/HTML-And-CSS-Template-2.webp";
import "../../assets/img website/HTML-And-CSS-Template-3.webp";
import "../../assets/img website/HTML-And-CSS-Template-4.webp";
import "../../assets/img website/quranPlayer-master.webp";
import "../../assets/img website/ramadan-2022.webp";
import "../../assets/img website/second-design-Bootstrap-3.webp";
import "../../assets/img website/Triks-and-Tips.webp";
import "../../assets/img website/Website-design-by-Sass.webp";
import "../../assets/img website/portfolio.webp";
