import "../../assets/01.jpg";
import "../../assets/02.png";
import "../../assets/03.png";
import "../../assets/04.png";
import "../../assets/05.png";
import "../../assets/06.png";
import "../../assets/07.svg";
import "../../assets/08.svg";
import "../../assets/09.svg";
import "../../assets/10.svg";
import "../../assets/11.svg";
import "../../assets/12.svg";
import "../../assets/13.png";
import "../../assets/14.png";
import "../../assets/15.png";
import "../../assets/icon.ico";
import "../../assets/logo.png";
import "../../assets/mockup1.png";
import "../../assets/mockup2.png";
import "../../assets/mockup3.png";
import "../../assets/mockup4.png";
import "../../assets/mockupMobile.png";
import "../../assets/mockupTalplet.png";
import "../../assets/mockupLabtop.png";
import "../../assets/mockupFullScreen.png";
import "../../assets/chart-arrow.png";
import "../../assets/img website/Admin-DashBoard.png";
import "../../assets/img website/Bootstrap-5-Design-02-Bondi.png";
import "../../assets/img website/Courses.png";
import "../../assets/img website/creat-responsev-web-dezain.png";
import "../../assets/img website/Creat-Templet-with-HTML-Css3-JavaScript.png";
import "../../assets/img website/creating-a-websit-from-privew-html-css-jQuery-LV3.png";
import "../../assets/img website/creating-a-websit-from-privew-html-css-jQuery.png";
import "../../assets/img website/first-design-Bootstrap-3.png";
import "../../assets/img website/first-design-Bootstrap-4.png";
import "../../assets/img website/first-design-Bootstrap-5.png";
import "../../assets/img website/HTML-And-CSS-Template-1.png";
import "../../assets/img website/HTML-And-CSS-Template-2.png";
import "../../assets/img website/HTML-And-CSS-Template-3.png";
import "../../assets/img website/HTML-And-CSS-Template-4.png";
import "../../assets/img website/quranPlayer-master.png";
import "../../assets/img website/ramadan-2022.png";
import "../../assets/img website/second-design-Bootstrap-3.png";
import "../../assets/img website/Triks-and-Tips.png";
import "../../assets/img website/Website-design-by-Sass.png";
import "../../assets/img website/portfolio.png";
